---
- name:  install tomcat on ubuntu
  hosts: appserver
  become: yes
  vars_files:
     - vars/tomcat_ubuntu_var.yaml

  tasks:
    - name: install java
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present  
      when: ansible_facts['distribution'] == "Ubuntu" 
    - name: install tomcat      
      user: 
        name: tomcat
        home: "{{tomcat_install_path}}"
        group: tomcat 
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"  
    - name: download tomcat
      get_url:
         url: "{{tomcat_download_source}}"
         dest: "{{tomcat_download_location}}"
      when: ansible_facts['distribution'] == "Ubuntu"  
    - name: unzip /opt/tomcat
      unarchive:
         src:  "{{tomcat_download_location}}"
         dest: "{{tomcat_install_path}}"
      when: ansible_facts['distribution'] == "Ubuntu"    