---
- name:  install tomcat on ubuntu
  hosts: appserver
  become: yes
  vars:
     username: tomact
     java_package: openjdk-8-jdk
     unzip_package: unzip
  vars_files:
     - vars/tomcat_ubuntu_var.yaml

  tasks:
    - name: install java
      apt:
        name: "{{java_package}}"
        update_cache: yes
        state: present  
      when: ansible_facts['distribution'] == "Ubuntu" 
    - name: create group
      group:
        name: "{{username}}"
        state: present
    - name: install tomcat      
      user: 
        name: "{{username}}"
        home: "{{tomcat_install_path}}"
        group: "{{username}}"
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"  
    - name: ensure unzip package in present
      package: 
        name: "{{unzip_package}}"
        state: present  
    - name: download tomcat
      get_url:
         url: "{{tomcat_download_source}}"
         dest: "{{tomcat_download_location}}"
      when: ansible_facts['distribution'] == "Ubuntu"  
    - name: unzip /opt/tomcat
      unarchive:
         src:  "{{tomcat_download_location}}"
         dest: "{{tomcat_install_path}}"
      when: ansible_facts['distribution'] == "Ubuntu"    